$ANSIBLE_VAULT;1.1;AES256
36333666363537303364386537626638626662613166306139633136323163613734656537363363
3863343633663862313763646239306664306366666363310a396434303661613864343466363931
62313335656139343831346233306338643261343432626161313939626432303131376131303330
6332316431333137360a326135353831353063313535303234343965353835623838383533663338
32313333393735353666663433343638656465626434303138643130363438656238303062623966
35396337353361656132353238386663363463363938393265616234313338646163643737663936
33363438353861343363613562303930316631373839336661633639316432333065666537663963
38613732356562643261346334373035626162333130653064613262313134633963376635373763
65633839626161343964633534356162653761396162363335336432396132326464323564616633
34643532386639303738653263363563663538386666656361323532666431633937376162653464
37633733306661616338316264303035653363653531623962393730323563623439333262383639
36393635336332323336663934323138346262653333663439393736386338633266663037643834
36353236333134323132336132623230333039303965356237383231393838393338343135666139
33346634333133306362363334643361316438336239393637376562633461373533393235623034
65363731303731323132323138343664663939666664333937613664303338303163333639353166
35386261306665616463623236326632333838363330313665623337396266383139646133343932
37626530643965313639376565326466626562356264326666663336366336303365343030336362
6165313962636631383134386664623135383266626464396631
